import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeWrapper } from '@/components/theme-wrapper';
import { QueryProvider } from './providers';
import { ProposalProvider } from '@/components/proposal-context';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adminstrasi - YAMAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeWrapper>
          <QueryProvider>
            <ProposalProvider>
              {children}
            </ProposalProvider>
          </QueryProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
